### ISSUE TITLE
Don't use extract-text-webpack-plugin in development

### ISSUE THREAD

**Issue by benjaminheng** [benjaminheng/subreddit-analytics#3]
Using this plugin prevents hot module reloading from working for CSS files. Switch to inline styles for development.

**Comment by benjaminheng** [comment]
Closed with b25b305b74ab56dd8275afa13276ae21793f7d68.

**Comment by IAMtheIAM** [comment]
No need to use inline styles. Just use this loader

`loader: style!css?sourceMap!sass?sourceMap&sourceComments`

And `require('my.scss')` your styles at the top of your component (if using angular2, **not in the @Component decorator**). You'll get hot module replacement with external css, and sass sourcemaps.
